version: '3'

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    &airflow-common-env
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@airflow-postgres/airflow_postgres_db
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__FERNET_KEY: 'Cl6YO7wUa2ZY7iOg9fR6uQIw7V+YF8E1Y9K4R3dfV+g='
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false' 
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags/
    AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
    AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT: "8793"
    AIRFLOW__LOGGING__WORKER_LOG_SERVER_HOST: airflow-scheduler
    AIRFLOW__API__TASK_SDK_ENDPOINT: http://airflow-webserver:8080/api/v1
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-webserver:8080/execution/"
    AIRFLOW__API_AUTH__JWT_SECRET: "82d07c1349682ca2fe7c32d0202a3194a8c76943ce0c6acf8cd0c860139c8e27"
    PYTHONUNBUFFERED: 1
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  volumes:
    - airflow-logs:/opt/airflow/logs
  depends_on:
    airflow-postgres:
      condition: service_healthy

services:
  transactional-postgres:
    image: postgres:17
    container_name: transactional_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactional_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d transactional_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - transactional_db:/var/lib/postgresql/data

  airflow-postgres:
    image: postgres:17
    container_name: airflow_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow_postgres_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d airflow_postgres_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - airflow db migrate
    environment:
      <<: *airflow-common-env
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@airflow-postgres/airflow_postgres_db
    depends_on:
      airflow-postgres:
        condition: service_healthy
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully # This is the key!
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
  
  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: always

volumes:
  transactional_db:
  airflow-logs: