name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prepare:
    name: Prepare dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            data_extraction/.venv
          key: uv-${{ runner.os }}-${{ hashFiles('data_extraction/uv.lock') }}

      - name: Install dependencies
        working-directory: data_extraction
        run: |
          uv sync --frozen

  build-lint:
    name: Build, lint & format
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
            path: ~/.cache/uv
            key: uv-${{ runner.os }}-${{ hashFiles('data_extraction/uv.lock') }}

      - name: Install uv
        run: |
            if ! command -v uv; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
            fi
    
      - name: Ruff lint
        working-directory: data_extraction
        run: |
          uv run ruff check .

      - name: Ruff format check
        working-directory: data_extraction
        run: |
          uv run ruff format --check .
